#!/usr/bin/env ruby

require_relative 'lib/cli'
require_relative 'lib/magick'
require_relative 'lib/pathname_extensions'
require_relative 'lib/shell'
require_relative 'lib/zip_extensions'
require 'pathname'
require 'set'
require 'slop'
require 'zip'

ARCHIVE_EXTENSIONS = Set['cbz']

def repackage_all(directory)
  directory.child_files(select_extensions:ARCHIVE_EXTENSIONS).each do |file|
    extension = file.extension
    puts(file.to_s)
    if Zip::File.garbage_directories?(file)
      puts('  Cleaning garbage directories')
      Zip::File.remove_garbage_directories(file)
    end
    if Zip::File.all_files_in_one_directory?(file)
      puts('  Moving files out of directory')
      Zip::File.move_files_out_of_directory(file)
    end
    if Zip::File.garbage_files?(file)
      puts('  Cleaning garbage files')
      Zip::File.remove_garbage_files(file)
    end
    if !Zip::File.files_numbered?(file)
      puts('  Renumbering')
      Zip::File.renumber_files(file)
    end
  end
end

repackage_all(Pathname.new('.'))

